package hello;
//package hello;
//
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;
//
//import hello.provScore;
//import hello.provScoreRepo;
//
//@Controller    // This means that this class is a Controller
// // This means URL's start with /demo (after Application path)
//public class MainController {
//	@Autowired // This means to get the bean called userRepository
//	           // Which is auto-generated by Spring, we will use it to handle the data
//	private provScoreRepo psRepo;
//
//	@GetMapping(path="provrank/add") // Map ONLY GET Requests
//	public @ResponseBody String addNewUser (@RequestParam String siteName
//			, @RequestParam double score) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//
//		provScore ps = new provScore(siteName,score);
//		psRepo.save(ps);
//		return "Saved";
//	}
//
//	@GetMapping(path="provrank/display")
//	public @ResponseBody Iterable<provScore> getAllScores() {
//		// This returns a JSON or XML with the users
//		return psRepo.findAll();
//	}
//}